### ISSUE TITLE
Seeking explanation for 0007 LeetCode question, reverseInt

### ISSUE THREAD

**Issue by muregii** [muregii/codeKenya#11]
Eeeh explain hii stuff.

public static int reverse (int x) {
        int rev = 0;

        while(x != 0) {
            int digit = x % 10; //gets the last digit of the int
            rev = (rev * 10) + digit; //reverses the last digit
            x /= 10; //goes to the next digit 
        }

        return rev;
    }

**Comment by SenZmaKi** [comment]
# Code
```java
public static int reverse(int x) {
    int rev = 0;

    while (x != 0) {
        int digit = x % 10; // gets the last digit of the int
        rev = (rev * 10) + digit; // reverses the last digit
        x /= 10; // goes to the next digit 
    }

    return rev;
}
```
# Explanation

## Modulus Operator (`%`)
First off, you have to understand how the modulus (`%`) operator works:

```python
z = x % y
# For example:
3 = 13 % 10
4 = 4 % 10
```

Here, `z` is the remainder when `x` is divided by `y`, and if `x` is smaller than `y`, then `z` is `x`.

## Division Assignment Operator (`\=`)
Secondly, `x /= 10` is basically the same as saying `x = x / 10`. Take note that in most programming languages, if both operands (`x` and `10` in this case) are integers (whole numbers), the decimal remainder gets truncated, leaving only the whole number. For example, if `x` is `13`, then `13 / 10 = 1` instead of `1.3`.

## Algorithm Walkthrough
Now, let's walk through the algorithm with an example (assuming `x` is 1234):

**Iteration 1**
```python
rev = 0
x = 1234
digit = 1234 % 10  # 4
rev = (0 * 10) + 4  # 4
x = 1234 / 10       # 123
```

**Iteration 2**
```python
rev = 4
x = 123
digit = 123 % 10   # 3
rev = (4 * 10) + 3  # 43
x = 123 / 10       # 12
```

**Iteration 3**
```python
rev = 43
x = 12
digit = 12 % 10   # 2
rev = (43 * 10) + 2  # 432
x = 12 / 10        # 1
```

**Iteration 4**
```python
rev = 432
x = 1
digit = 1 % 10   # 1
rev = (432 * 10) + 1  # 4321
x = 1 / 10       # 0
```

At this point, `x = 0`, hence the loop breaks, and the function returns with `rev`, which is `4321`.

## Key Sections of the Algorithm
This algorithm has 3 main sections:
- Retrieving the last digit using the modulus.
- Appending the retrieved digit to the reversed number, done by multiplying the reversed number by 10 and adding the reversed digit.
- Cutting off the last digit so that the next iteration works with the current second last digit, done by dividing by 10.

The number 10 is really important here because it represents the place value of the last digit, which is used both during appending and cutting off.

**Comment by muregii** [comment]
Logic well explained. I'd just add this. Based on an edge case that Leetcode demands of the range of rev.

<img width="473" alt="Screenshot 2023-12-07 at 1 26 47 AM" src="https://github.com/muregii/codeKenya/assets/88530358/e3861f2b-26bd-4a07-894b-5924322d0438">

long rev = 0; 
     
          if(rev > Integer.MAX_VALUE || rev < Integer.MIN_VALUE){
              return 0;
          }
      
      return (int) rev; 
    }

1. Use long to anticipate any overflows that int may not account for.
2. Also add the conditional Integer.MAX_VALUE and Integer.MAX_VALUE to enforce the range constraint. Return 0.
3. Remember to explicitly cast your long type back to (int) in your return statement.
